### ISSUE TITLE
error when updating symfony/process 4.3.8 to 4.4.1

### ISSUE THREAD

**Issue by jstolp** [laravel/envoy#177]
- Envoy Version: v1.6.4
(symfony/process v4.4.1)
- Laravel Version: v.6.6.0
- PHP Version: 7.2.x
- Database Driver & Version:

### Description:

When reading a command line argument it throws this error.

In Process.php line 1648:
 
 Command line is missing a value for key "$KEY_NAME_HERE"

### Steps To Reproduce:

Seems to be the same issue as: https://github.com/laravel/valet/pull/843

If i downgrade to 4.3.8 it works fine...

Or should I report this to the _symfony/process_ repo?

**Comment by driesvints** [comment]
Can you post the full stacktrace?

**Comment by jstolp** [comment]
So this is the full output from jenkins.
We use a BASH script to update. we pass those values from Envoy to the Bash script.
I've modified the output a bit to hide urls and such...

In this example i updated 

```
Started by upstream project "Deployments/hidden.com" build number 123
originally caused by:
 Started by user hidden.com
Running as SYSTEM
Building on master in workspace ****
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent] Exec ssh-agent (binary ssh-agent on a remote machine)
$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-****/agent.1234
SSH_AGENT_PID=12345
[ssh-agent] Started.
Running ssh-add (command line suppressed)
Identity added: ***
[ssh-agent] Using credentials ****
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url hidden.com/forms.git # timeout=10
Fetching upstream changes from hidden.com/forms.git
 > git --version # timeout=10
using GIT_SSH to set credentials Bitbucket
 > git fetch --tags --progress git@hidden.com/forms.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/some-branch^{commit} # timeout=10
Checking out Revision revision_here (origin/some branch)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f revision_here
Commit message: "some commit message"
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/jenkins8400396435090136261.sh
+ git config --local user.name 'Jenkins Autodeployer'
+ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 43 updates, 0 removals
 - Updating pyrech/composer-changelogs (v1.6.0 => v1.7.0): Loading from cache
 - Updating doctrine/lexer (1.1.0 => 1.2.0): Loading from cache
 - Updating guzzlehttp/guzzle (6.3.3 => 6.4.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (50%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating symfony/process (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (40%)Downloading (80%)Downloading (85%)Downloading (100%)
 - Updating symfony/service-contracts (v1.1.7 => v2.0.1): Downloading (connecting...)Downloading (0%) Downloading (100%)
 - Updating symfony/polyfill-php73 (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (65%)Downloading (100%)
 - Updating symfony/polyfill-mbstring (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (30%)Downloading (60%)Downloading (90%)Downloading (100%)
 - Updating symfony/console (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating symfony/polyfill-ctype (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (100%)
 - Updating phpoption/phpoption (1.5.0 => 1.6.0): Downloading (connecting...)Downloading (0%) Downloading (80%)Downloading (100%)
 - Updating symfony/css-selector (v4.3.5 => v5.0.1): Loading from cache
 - Updating symfony/polyfill-php72 (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (80%)Downloading (100%)
 - Updating symfony/var-dumper (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (15%)Downloading (25%)Downloading (30%)Downloading (45%)Downloading (50%)Downloading (60%)Downloading (70%)Downloading (80%)Downloading (85%)Downloading (95%)Downloading (100%)
 - Updating symfony/routing (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (40%)Downloading (50%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating symfony/polyfill-intl-idn (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (45%)Downloading (100%)
 - Updating symfony/mime (v4.3.5 => v5.0.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (15%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (55%)Downloading (60%)Downloading (70%)Downloading (80%)Downloading (85%)Downloading (95%)Downloading (100%)
 - Updating symfony/http-foundation (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating symfony/event-dispatcher (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (45%)Downloading (90%)Downloading (100%)
 - Updating psr/log (1.1.0 => 1.1.2): Loading from cache
 - Updating symfony/debug (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (20%)Downloading (30%)Downloading (40%)Downloading (90%)Downloading (100%)
 - Installing symfony/error-handler (v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (15%)Downloading (25%)Downloading (35%)Downloading (40%)Downloading (50%)Downloading (55%)Downloading (65%)Downloading (75%)Downloading (90%)Downloading (100%)
 - Updating symfony/http-kernel (v4.3.5 => v4.4.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating symfony/finder (v4.3.5 => v4.4.1): Loading from cache
 - Updating symfony/polyfill-iconv (v1.12.0 => v1.13.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (100%)
 - Updating swiftmailer/swiftmailer (v6.2.1 => v6.2.3): Loading from cache
 - Updating ramsey/uuid (3.8.0 => 3.9.1): Downloading (connecting...)Downloading (0%) Downloading (10%)Downloading (15%)Downloading (25%)Downloading (35%)Downloading (45%)Downloading (60%)Downloading (70%)Downloading (75%)Downloading (85%)Downloading (100%)
 - Updating opis/closure (3.4.1 => 3.5.1): Downloading (connecting...)Downloading (0%) Downloading (20%)Downloading (55%)Downloading (75%)Downloading (100%)
 - Updating symfony/translation-contracts (v1.1.7 => v2.0.1): Downloading (connecting...)Downloading (0%) Downloading (100%)
 - Updating symfony/translation (v4.3.5 => v4.4.1): Loading from cache
 - Updating nesbot/carbon (2.25.3 => 2.27.0): Loading from cache
 - Updating monolog/monolog (1.25.1 => 2.0.1): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating doctrine/inflector (v1.3.0 => 1.3.1): Loading from cache
 - Updating laravel/framework (v5.8.35 => v6.6.0): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating laravel/envoy (v1.6.1 => v1.6.4): Downloading (connecting...)Downloading (0%) Downloading (45%)Downloading (70%)Downloading (100%)
 - Updating nikic/php-parser (v4.2.4 => v4.3.0): Loading from cache
 - Updating psy/psysh (v0.9.9 => v0.9.11): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating fzaninotto/faker (v1.8.0 => v1.9.0): Loading from cache
 - Updating mockery/mockery (1.2.4 => 1.3.0): Loading from cache
 - Updating sebastian/environment (4.2.2 => 4.2.3): Loading from cache
 - Updating phpunit/php-code-coverage (7.0.8 => 7.0.10): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
 - Updating webmozart/assert (1.5.0 => 1.6.0): Loading from cache
 - Updating doctrine/instantiator (1.2.0 => 1.3.0): Loading from cache
 - Updating phpunit/phpunit (8.4.1 => 8.4.3): Downloading (connecting...)Downloading (0%) Downloading (5%)Downloading (10%)Downloading (15%)Downloading (20%)Downloading (25%)Downloading (30%)Downloading (35%)Downloading (40%)Downloading (45%)Downloading (50%)Downloading (55%)Downloading (60%)Downloading (65%)Downloading (70%)Downloading (75%)Downloading (80%)Downloading (85%)Downloading (90%)Downloading (95%)Downloading (100%)
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
+ ./vendor/bin/envoy run deploy --env=test-env --branch=some-branch --asVersion=1.0.0

In Process.php line 1648:
 
 Command line is missing a value for key "$DEPLOY_GIT_TYPE": ssh -A user@server 'bash -se' << \EOF-LARAVEL-ENVOY 
 export ENVOY_HOST="-A user@server.com 
 
 set -e 
 # This is bash code, not PHP 
 DEPLOY_TIMESTAMP="test-env-20191202141526" 
 DEPLOY_GIT_POINTER="git-pointer" 
 DEPLOY_GIT_TYPE="branch" 
 DEPLOY_ENV="test-env" 
 USES_VERSIONS= 
 
 WEBAPP_USER="user" 
 WEBAPP_GROUP="user" 
 RELEASE_ENV="test-env" 
 
 SHARED_PATH="/var/www/some-folder/shared/" 
 
 VERSION_SPECIFIC_ENV_PATH="/var/www/some-folder/test-env/bla/bla" 
 
 WEBAPP_PATH="/var/www/some-folder/bla/bla" 
 DEPLOY_PATH="/var/www/some-folder/bla/bla/deploy/path" 
 


# more code for deploy
# snipped for github.com issue...

 if [ "$DEPLOY_GIT_TYPE" == "tag" ]; then 
 # if we are deploying a tag (with a specific version) 
 # check that the version specific env file exists. 
 if [ ! -d $VERSION_SPECIFIC_ENV_PATH ]; then 
 echo "Missing shared path for specific version $VERSION_SPECIFIC_ENV_PATH"; 
 exit 1; 
 fi 
 
 echo " - Mark the new release as down" 
 php $DEPLOY_PATH/artisan down 
 EOF-LARAVEL-ENVOY. 
 

run [--continue] [--pretend] [--path PATH] [--conf CONF] [--] <task>

Build step 'Execute shell' marked build as failure
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 1234 killed;
[ssh-agent] Stopped.
Finished: FAILURE
```

**Comment by jstolp** [comment]
in Envoy.blade.php we have this script:

We setup the variables for use:

```
// These variables are used later on in the script
    $RELEASE_VCS_TYPE           = $releaseVcsType;
    $SERVERS                    = array_keys($active_env['servers']);
    $TARGET_ENV                 = $env;
    $WEBAPP_PATH                = $active_env['webapp_path'];
    $SHARED_VERSION_ENV_PATH    = $active_env['webapp_path'] . "/shared/";
    $SHARED_PATH                = $active_env['shared_path'];
```

Then in the deploy-code step in envoy we use those values:

```
@task('deploy-code', ['on' => $SERVERS, 'parallel' => true])
    # This is bash code, not PHP
    DEPLOY_GIT_TYPE="{{ $RELEASE_VCS_TYPE }}"
    WEBAPP_USER="{{ $WEBAPP_USER }}"
    WEBAPP_GROUP="{{ $WEBAPP_GROUP }}"
    RELEASE_ENV="{{ $TARGET_ENV }}"
... ect. ect.
```

**Comment by jstolp** [comment]
@driesvints do you have enough info to conclude what's wrong?

**Comment by mcallan83** [comment]
I am also experiencing this:

```
  Command line is missing a value for key "$purging": ssh -A deployer@staging.gonorth.io 'bash -se' << \EOF-LARAVEL-ENVOY
  export ENVOY_HOST="-A deployer@staging.gonorth.io"

  set -e
  purging=$(ls -dt /var/www/crm/releases/* | tail -n +6);

  if [ "$purging" != "" ]; then
  echo "[DEPLOYER] Purging Old Releases"
  rm -rf $purging
  fi;
  EOF-LARAVEL-ENVOY.
```

**Comment by fideloper** [comment]
This is related to this garbage:

![image](https://user-images.githubusercontent.com/467411/70259863-b6377180-1754-11ea-98a4-ae82069e08a2.png)

(from symfony docs: https://symfony.com/doc/4.4/components/process.html)

When using `Process:: fromShellCommandline($cmd)`, anything starting with `$` in your  `$cmd` is run through a find/replace:

![image](https://user-images.githubusercontent.com/467411/70259932-debf6b80-1754-11ea-8103-82b0d9b29937.png)


It expects any bash/shell variables to be pre-defined as an environment variable (which is a TERRIBLE assumption).

I can't find a way around this, so my work around has been something like this:

```php
$process = Process::fromShellCommandline('echo "$MESSAGE!"');

$process->run(null, ['MESSAGE' => '$MESSAGE']);
```

...which is terrible (You can tell I'm pretty peeved by this change :D )

**Comment by jstolp** [comment]
We are in for a treat.... We use Mac, Unix and windows... Pretty mixed. I'll see if I can find a nice solution for this tomorrow.

**Comment by fideloper** [comment]
Haven’t tested, but this looks promising:
https://github.com/symfony/symfony/issues/34838#issuecomment-562249796

That being said, I’m unsure if that’s valid in Windows

**Comment by jstolp** [comment]
Thanks for the pointer, I'll try it out tomorrow!

**Comment by driesvints** [comment]
This is technically a Symfony problem as pointed out by @fideloper but I'm gonna leave this open for a bit to see how this plays out. There's currently a discussion going on on the PR that introduced the change: https://github.com/symfony/symfony/pull/32126

**Comment by jstolp** [comment]
There might be a revert of this change :) 
https://github.com/symfony/symfony/pull/34845

**Comment by driesvints** [comment]
@jstolp can you confirm this was fixed if you update tot he latest 4.x version of symfony/process?

**Comment by jstolp** [comment]
@driesvints I can confirm this is fixed, with the v4.4.2 version of _symfony/process_
Thanks for your help! And happy coding in 2020!

**Comment by itguy614** [comment]
I believe this is still a problem.  I have tried various combinations of envoy 1.6.1 - 1.6.4 and symfony/process 4.3 - 5.0.
